### ISSUE TITLE
Update project auto-detection to use siteinfo

### ISSUE THREAD

**Issue by robertodauria** [m-lab/bmctool#35]
Project auto-detection currently relies on an outdated assumption that all the mlab4s are staging nodes and mlab[1-3] are production nodes. This is not true anymore, and [siteinfo](https://siteinfo.mlab-oti.measurementlab.net/v2/sites/sites.json) is the source of truth to follow.

**Comment by nkinkade** [comment]
@robertodauria: Looking at this more closely now, this is definitely note done. Any thoughts on how this could sensibly be implemented, since the tool would need to make a determination about which project the machine is in at run time? It sort of feels like making an HTTP call to siteinfo and parsing the output in real-time might not be the right thing? Then again, maybe it is fine, since it would likely only add not more than 1 to 2 seconds of extra lag time on each invocation of bmctool?
