### ISSUE TITLE
Add subcommand to tunnel to the BMC via another host

### ISSUE THREAD

**Issue by evfirerob** [m-lab/bmctool#6]
bmctool should have a subcommand like `bmctool forward <host> <bmc> --ports 443,5900` to create an SSH tunnel via `<host>` to the specified `<bmc>`.

bmctool should then keep running on the foreground.

Also, there could be an alias like `bmctool web <host> <bmc>` to forward ports that are useful to access the BMC web interface, or we could just make 443,5900 the default value for the `--ports` flag. @stephen-soltesz @nkinkade any thoughts on this?

**Comment by stephen-soltesz** [comment]
I suggest adding sensible defaults so that the common usage looks like: `bmctool forward <bmc>` -- where `<bmc>` is any of the standard node / drac abbreviations i.e. mlab1.abc01, mlab1d.abc01, or the long forms.

I think it would be okay to make the forwarding host, e.g. eb, a flag rather than a positional parameter since most of the time we'll rely on the default. Are there different use cases for `forward` and `web`? "web console & service access" is all I've ever used it for.
